### ISSUE TITLE
Can't upload a cookbook from non-master branch

### ISSUE THREAD

**Issue by akoldaev** [schubergphilis/chef-guard#101]
Steps to reproduce:
- Create a git branch for a cookbook
- Make changes in a recipe
- Bump the version in metadata.rb
- Commit and push changes to a remote branch
- Try uploading with --freeze flag

Getting this one:

> Make sure all your changes are merged into the central
> repositories before trying to upload the cookbook again.

**Comment by svanharmelen** [comment]
@iroller this behaviour is by design... If you want to freeze somethings (and so thread it as released) that is not in `master`, you set manually set a tag on the commit you want to use...

**Comment by akoldaev** [comment]
Oh great, it was easy :+1: Thanks @svanharmelen
