### ISSUE TITLE
Look for cookbook name in metadata.rb when checking forks

### ISSUE THREAD

**Issue by akoldaev** [schubergphilis/chef-guard#103]
A lot of the cookbooks on github are named "chef-cookbook-name" or something like that instead of the actual cookbook name.

When forking I prefer to preserve the repo name so there's less confusion for someone else looking at fork.

When Chef-Guard is checking the cookbook being uploaded it's trying to find cookbook name in forks and it fails with

```
=== Cookbook Compare errors found ===
You are trying to upload 'cookbook-name' version '1.0.0' which is a
non-existing version of a community cookbook! Make sure you are using
an existing community version, or a fork with a pending pull request.
=====================================
```

**Comment by svanharmelen** [comment]
The problem with this is the amount of time and effort needed to find the correct repo (if it even exists). We would need to scan each and every repo in your folk organization to see if the repo has a metadata.rb. And for every repo that has a metadata.rb we would need to parse it to see if it matches the cookbook we are searching for....

So I get your point, but I doubt if it is a big enough issue to move from the single HTML GET call we have to do now, to the full blown search logic (which makes at least one call per repo in your fork org and needs to parse all metadata.rb files it encouters) needed to do what you are suggesting...

**Comment by svanharmelen** [comment]
Thought about this one for a while, but for the time being I'm not going to add this kind of logic.

So closing this as a _won't fix_ for now, feel free to reopen the issue if there are any new compelling reasons that might change my point of view.
