### ISSUE TITLE
`knife data bag from file` fails when using a json saved by Chef-Guard

### ISSUE THREAD

**Issue by akoldaev** [schubergphilis/chef-guard#105]
We're having the data bags commited by Chef-Guard in the following format:

``` json
{
  "chef_type": "data_bag_item",
  "data_bag": "dns_records",
  "json_class": "Chef::DataBagItem",
  "name": "data_bag_item_dns_records_sm_domain_com",
  "raw_data": {
    "chef_type": "data_bag_item",
    "data_bag": "dns_records",
    "fqdn": "sm.domain.com",
    "id": "sm_domain_com",
    "ttl": 300,
    "type": "A"
  }
}
```

This format doesn't let us to re-create this data bag using `knife data bag from file`:

```
ERROR: Chef::Exceptions::InvalidDataBagItemID: Data Bag items must have an id matching /^[\.\-[:alnum:]_]+$/, you gave: nil
```

Is it a known issue? Was it discussed before? Is there any way to save it in a format which will work for `knife`?

I remember we discussed it with @svanharmelen before but can't recall what was the outcome. Would appreciate a reminder.

**Comment by svanharmelen** [comment]
Not sure if this is something I would like to add. The data written to Github is the data as seen by Chef-Guard. In some cases this is a format that can be used directly to recreate the entity, but in the case of a data bag that's not the case. Not sure how the format should look at to make that work, but it would mean we would have to do some custom transformations on the data which we currently do not do.

But even without being able to directly recreate the data bag from the saved data, you still have access to all data (keys and values) needed to recreate the bag. So there is no real need for this other than that it makes life a little easier when you have to fix/restore something after a human error is made (wrongly deleting or overwriting the bag). But that should be a rare use case right?

**Comment by akoldaev** [comment]
In our case it's a very frequent issue. We tried to switch to editing data bags directly with `knife data bag edit` and it always a headache when you miss a comma or make another syntax error and it doesn't save your changes. Much easier to edit a file and do `knife data bag from file`.

There's also a number of command line tools that make editing files easier (e.g. sed/awk for multiple files at once). After using Chef-Guard for a while and trying it's approaches of directly editing the data bags we're still missing the ease of editing files and uploading them with `knife data bag from file` or `knife role from file`.

**Comment by svanharmelen** [comment]
@iroller I'm going to close this one as a wouldn't fix...

The things Chef-Guard is saving are meant to be used for auditing, to give insights in the changes your collega's made and to be able to retrieve lost data when wrongly deleting or overwriting an object.

I fully understand your use case, but I think for that you should just maintain a separate [chef-repo](https://docs.chef.io/chef_repo.html) with the files in there for maintaining your data bags.

Having said that, if a proper PR comes along there is still a very good change I'll merge it. It's just not going to be on the Chef-Guard roadmap...

Thanks!
