### ISSUE TITLE
chef-guard running, but nothing being mailed or committed

### ISSUE THREAD

**Issue by steveberryman** [schubergphilis/chef-guard#112]
Chef guard installed correctly, and a tcpdump and strace on the port and process seem to imply that it's running and chef/knife traffic is passing through it, but it's not validating, committing or mailing any configuration changes despite all the options for that being enabled.

I suspect I've done something wrong somewhere but there is nothing at all in the logs other than the service starting message.

chef-guard 0.7
chef 12

**Comment by svanharmelen** [comment]
@steveberryman hmm, that doesn't sound good. Could you maybe share your (obfuscated) config? And did you also do [this](http://xanzy.io/projects/chef-guard/installation/installation.html#chef-12)? Even if you used the cookbook, you should still do this one manual step.

**Comment by steveberryman** [comment]
Here's my config:
https://gist.github.com/steveberryman/c1c3d3d3406b5df13e2e8965055b597a

my /opt/opscode/embedded/cookbooks/private-chef/attributes/default.rb line is set to this:
`default['private_chef']['lb']['upstream']['opscode-erchef'] = [ "127.0.0.2" ]`

in /var/opt/opscode/nginnx/etc/nginx.conf it has this section (which i think is the operative one):
`upstream opscode_erchef {
    server 127.0.0.2:8000;
  }`

Thanks!

**Comment by svanharmelen** [comment]
@steveberryman very strange as that all seems to be OK. Let's do a simple test... What happens if you stop Chef-Guard and try to upload a cookbook or do a Chef-Client run? Of course that should now fail, but I wonder if it really does...

As for your customer config, just `[customer "compose"]` should be enough as the other config is the same as your default config. So you may just omit them which causes your defaults to be used. 

And I assume the name `compose` is the shortname of the Chef organization you are trying to guard (so your knife config contains something like `chef_server_url 'https://chef.company.com/organizations/compose'`)?

**Comment by steveberryman** [comment]
I thought it was odd as well!

OK, if i stop chef guard, chef stops working with a 502 error: 
`[2016-10-31T09:04:58+00:00] ERROR: Server returned error 502 for https://chef.compose.com/nodes/nodename, retrying 1/5 in 4s`

Started it again and the chef run completed as expected, so traffic is definitely passing through chef-guard.

wrt the organisation, compose is the shortname of the chef organisation i'm trying to guard (the only organisation listed when i run `root@chef bin $chef-server-ctl org-list`. However, my knife config simply has the chef hostname, not the full path to the organization/compose bit, as do all my nodes `client.rb' files, so maybe this is the problem!

**Comment by steveberryman** [comment]
A quick test of changing my knife configuration was a success! I don't suppose there's an easy way of telling chef-guard that a certain organisation is the default one?

**Comment by Tech356** [comment]
This is the same as what I saw in issue #73.

**Comment by svanharmelen** [comment]
@steveberryman yes, this is probably the same as problem @Tech356 pointed out. In that case you have probably done an inplace upgrade from open source Chef 11 to Chef 12, right?

I looked at supporting that situation once, but didn't get to actually merging any fixes. I'm pretty busy at the moment, but I will see if I can add support for this use case.

**Comment by steveberryman** [comment]
It was that problem - I've updated all the urls now so it works fine. A
simple 'fix' might just be to mention it in the docs :)

**Comment by svanharmelen** [comment]
@steveberryman yes, that is definitely something I will do (update the docs!)... And will check if we can support it properly as well, but that will take time.

Good that it's working now for you! I'll close this issue and will follow up in issue #73
