### ISSUE TITLE
502 Error when Git repo is empty

### ISSUE THREAD

**Issue by jordan3825** [schubergphilis/chef-guard#115]
When uploading a cookbook where the Git repo has been created, but code has not yet been pushed, Chef-Guard throws a 502 error.

    C:\chef-repo>knife cookbook upload mycookbook --freeze
    Uploading mycookbook [0.1.0]
    ERROR: Server returned error 502 for https://chef.company.com/organizations/myorg/cookbooks/mycookbook/0.1.0, retrying 1/5 in 4s

The Chef-Guard log contains:

    ERROR: Error retrieving tags of repo mycookbook: GET https://github.company.com/api/v3/repos/myorg/mycookbook/git/refs/tags/v0.1.0: 409 Git Repository is empty. []

I would expect Chef-Guard to throw a more descriptive error. Something like 

    Precondition Failed: Git repo is empty

**Comment by svanharmelen** [comment]
@jordanmwright but what does the error say after the 5th retry? As that is the error that Chef-Guard generates. The error you're seeing here is generated by `knife`.

**Comment by jordan3825** [comment]
Here is the entire output:

    C:\chef-repo>knife cookbook upload mycookbook --freeze
    Uploading myorg           [0.1.1]
    ERROR: Server returned error 502 for https://chef.company.com/organizations/myorg/cookbooks/mycookbook/0.1.1, retrying 1/5 in 3s
    ERROR: Server returned error 502 for https://chef.company.com/organizations/myorg/cookbooks/mycookbook/0.1.1, retrying 2/5 in 6s
    ERROR: Server returned error 502 for https://chef.company.com/organizations/myorg/cookbooks/mycookbook/0.1.1, retrying 3/5 in 9s
    ERROR: Server returned error 502 for https://chef.company.com/organizations/myorg/cookbooks/mycookbook/0.1.1, retrying 4/5 in 26s
    ERROR: Server returned error 502 for https://chef.company.com/organizations/myorg/cookbooks/mycookbook/0.1.1, retrying 5/5 in 64s
    ERROR: bad gateway
    Response: Error retrieving tags of repo myorg: GET https://github.company.com/api/v3/repos/myorg/mycookbook/git/refs/tags/v0.1.1: 409 Git Repository is empty. []

It does show the proper error at the end. Is Chef-Guard returning the 502? It seems to me that it shouldn't be retrying 5 times for something that won't be fixed by retying.

**Comment by svanharmelen** [comment]
Indeed the 502 is returned by Chef-Guard... So indeed we could check if we can change the exception code to one that doesn't cause the retries to happen...

**Comment by svanharmelen** [comment]
Fixed by PR #117
