### ISSUE TITLE
How to fetch bookshelf key and secret

### ISSUE THREAD

**Issue by poblahblahblah** [schubergphilis/chef-guard#123]
Hello,

It looks like for more recent versions of chef server (we are using 12.16.14-1 on Ubuntu 16.04), the private-chef-secrets.json file contains encrypted data. Since it's encrypted we're unable to fetch the bookshelf key and secret from here. Do you know of a way to decrypt this so we can grab that info?

**Comment by svanharmelen** [comment]
Interesting... I would guess the decryption is done by something (e.g. PSK, cert) that is available on the Chef server.

But this one requires some digging to find out. Think it means going through the Chef (Erlang) code to figure out how and where it is decrypted...

**Comment by poblahblahblah** [comment]
I forgot to update this - I pretty quickly figured out how to grab the key from the server. I'll get a PR going at https://github.com/xanzy/xanzy.github.io/tree/master/projects/chef-guard and update the information there.

**Comment by svanharmelen** [comment]
Ah, cool! Thanks 👍

**Comment by poblahblahblah** [comment]
Here's the PR: https://github.com/xanzy/xanzy.github.io/pull/3

Just to note for anyone viewing this issue - the file with the bookshelf key and secret are in /etc/opscode/chef-server-running.json for Chef Server 12.16.14

**Comment by svanharmelen** [comment]
Merged... Thx!
