### ISSUE TITLE
Add GitLab API v4 support

### ISSUE THREAD

**Issue by ghost** [schubergphilis/chef-guard#128]
GitLab recently dropped support for the v3 API:

- https://docs.gitlab.com/ee/api/v3_to_v4.html

This change results in slightly different URL's that are used for the GitLab v4 API, as a result we now have 404 (not found) errors when chef-guard tries to work with the GitLab API.

Please add support for the v4 API.

Thanks!

**Comment by svanharmelen** [comment]
@bgroenendal I think this only needs a configuration change in your [git sections](http://xanzy.io/projects/chef-guard/configuration/git_section.html). If you update the URLs in there to end with `v4` instead of `v3`, you should be good.

**Comment by ghost** [comment]
When I change the URL i keep getting the 404 errors:

`ERROR:   2018/11/14 10:53:01 Failed to update cookbook ***** for bgroenendal in git: Error creating file cookbooks/****.json: POST https://gitlab.*****/api/v4/projects/chef-guard/***/repository/files: 404  []`

I'm using the 0.4.2 version of the chef-guard cookbook.

**Comment by ghost** [comment]
My current configuration:

`'serverurl' => 'https://gitlab.****/api/v4/',`

**Comment by ghost** [comment]
The API does seem to work when I manually test it:

`curl -k --request GET --header "PRIVATE-TOKEN: *****" https://gitlab.***/api/v4/search?scope=projects\&search=role`

This gives me all projects with 'role' in the name. The token is the same as configured for chef-guard.

When I check the gitlab logs I do see connections, but for some reason I keep getting this error:

`{"error":"404 Not Found"}`

Am I using the correct version of the Chef-Guard cookbook?!

**Comment by svanharmelen** [comment]
I don't think this is related to the Chef-Guard cookbook. I suspect it has something to do with the repo and/or location of the files.

Did this setup work before, or is this a new setup? And does the `cookbook` directory already exist in the target repo?

I could be that this is related to a Gitlab update, I started to create a new release with the latest dependencies but I'm waiting for confirmation from @rarenerd if that version is good to go.

Once that is released you could/should give that try to see if it fixes this issue.

**Comment by ghost** [comment]
The setup did indeed work before. It became broke after a gitlab upgrade/update.

The cookbook folder exists and already contains files from previous uploads. E.g., the specific cookbook that I'm uploading already exists in an older version.

I'm assuming the gitlab update broke "something".

I do however see that the connection is being made towards the GitLab server, during the upload of 1 cookbook. Chef-guard reports 1 "not found" error, but on the gitlab end there are 3 queries being made.

The first query gives a 200 status, the other two come back with a 404 not found.

`{"time":"2018-11-14T11:06:00.148Z","severity":"INFO","duration":49.64,"db":15.36,"view":34.28,"status":200,"method":"GET","path":"/api/v4/projects/****_chef-guard%2F****/repository/tree","params":{"path":"cookbooks/****_role_chef-guard-1.0.6.json"},"host":"gitlab.****.****.nl","ip":"***.***.***.***.","ua":"go-gitlab/0.1.1","route":"/api/:version/projects/:id/repository/tree","user_id":5,"username":"chef-guard","queue_duration":7.57,"gitaly_calls":2}`

`{"time":"2018-11-14T11:06:00.161Z","severity":"INFO","duration":0.61,"db":0.0,"view":0.61,"status":404,"method":"GET","path":"/api/v4/projects/****_chef-guard%2F****/repository/files","params":{"file_path":"cookbooks/****_role_chef-guard-1.0.6.json","ref":"master"},"host":"gitlab.****.****.nl","ip":"***.***.***.***.","ua":"go-gitlab/0.1.1","route":"/api/:version/*path","queue_duration":6.21,"gitaly_calls":0}`

`{"time":"2018-11-14T11:06:00.171Z","severity":"INFO","duration":0.95,"db":0.0,"view":0.95,"status":404,"method":"POST","path":"/api/v4/projects/****_chef-guard%2F****/repository/files","params":{"file_path":"cookbooks/****_role_chef-guard-1.0.6.json","branch_name":"master","author_email":"bgroenendal@****.nl","author_name":"bgroenendal","content":"[FILTERED]","commit_message":"Config for cookbook ****_role_chef-guard-1.0.6 created by Chef-Guard"},"host":"gitlab.****.****.nl","ip":"***.***.***.***.","ua":"go-gitlab/0.1.1","route":"/api/:version/*path","queue_duration":6.11,"gitaly_calls":0}`

**Comment by ghost** [comment]
I've found the issue.

I'm using the chef-guard cookbook from supermarket.chef.io, which is version 0.4.2.
When I check the changelog it mentions the chef-guard version v0.7.1 in 0.4.1 but doesn't mention v0.7.2 which is visible as a release on GitHub.

- https://github.com/xanzy/chef-guard/releases/tag/v0.7.2

The changelog of this version mentions support for the gitlab api v4.

I've now manually downloaded chef-guard version 0.7.2 (from june) and replaced the chef-guard executable on my server (including a restart of the application). While doing so, I now have a working setup with support for the new gitlab v4 api.

Can you please update the chef-guard cookbook on the supermarket to also contain the v0.7.2 version of chef-guard?

**Comment by svanharmelen** [comment]
Glad to hear that solved the problem @bgroenendal!

You shouldn't have to download the binary manually as the cookbook already supports using different versions. It should be enough to change the Chef-Guard `version` and `checksum` attributes to make it use any version your want: https://github.com/xanzy/chef-guard-cookbook/blob/master/attributes/default.rb#L21

We are currently working on a new release, so I will wait until that one is out before I'll update the cookbook to point it to the latest version as the new default.
