### ISSUE TITLE
Cache support

### ISSUE THREAD

**Issue by johnewart** [schubergphilis/chef-guard#44]
Support caching of result data with a cache (groupcache, memcache with consistent hashing algorithm, etc.) and a JSON language to specify how to invalidate cache (request matches, time, etc.)

**Comment by johnewart** [comment]
I'm working on this but can't assign it to myself, I'll open a PR when I have something

**Comment by svanharmelen** [comment]
Nice :+1:

**Comment by bscott** [comment]
Awesomeness! +1

**Comment by sbotman** [comment]
Hi John, 

How is it going with the cache support?
Do you have any progress on this?

Gr Sander

**Comment by svanharmelen** [comment]
Closing this one due to inactivity and lack of response...
