### ISSUE TITLE
Archive uploaded to supermarket should not contain files that are in the chefignore/gitignore.

### ISSUE THREAD

**Issue by sbotman** [schubergphilis/chef-guard#56]
While doing the file compare, some files are left and checked against the ignore files. These files also end-up in the tar that's uploaded to the supermarket. We should drop these files and make more clean archives, because you could have errors on files that are different and in the ignore if the chefignore is not respected (like when using knife)

**Comment by svanharmelen** [comment]
Fixed by PR #74
