### ISSUE TITLE
Support for GitLab

### ISSUE THREAD

**Issue by paulbadcock** [schubergphilis/chef-guard#61]
I have a client that currently runs a private GitLab server for code repository. Are there any plans to add GitLab or any support besides GitHub?

**Comment by svanharmelen** [comment]
@PaulBad yes, we definitely want to add support for Gitlab. Currently I don't think we are planning to add any other backends, but of course we are open for suggestions and PR's!

The time frame for this is a little unclear, but I hope to target this for coming month (Nov, 2014)

**Comment by Tech356** [comment]
I would also like to add my support of this enhancement.

**Comment by tejaycar** [comment]
Any chance of adding support for plain it repos, or are we too tightly tied to needing an API?

**Comment by svanharmelen** [comment]
@tejaycar yeah, currently we would like to stick to using API's to communicate to other components. So using plain git repos directly from CG is not on the roadmap...

**Comment by lrosenberg-hotwire** [comment]
Any word on when/if chef-guard will get gitlab support? We'd definitely be interested in this since we prefer to use an internal gitlab repo instead of github.

**Comment by svanharmelen** [comment]
@lrosenberg-hotwire `if` is not the question... Chef-Guard will definitely get support for Gitlab! So `when` is the real question here.

As I'm currently working on a new release I will have a look at it this week. But depending on the amount of work it will take it could very well be postponed until the next release (which isn't planned yet). So it will either be very soon (within 14 days) or it will take some time (6 to 8 weeks probably).

**Comment by Tyrael** [comment]
@svanharmelen any update on this?

**Comment by svanharmelen** [comment]
@Tyrael this is one of those things that just keeps dangling at the bottom of my ToDo list :disappointed: I started with the implementation back in Februari, but about half way in got distracted with other higher prio stuff. I'm now on holiday, but will try to put it back on the map as soon as I get back in a week or two.

So I'm still convinced this will be landing in Chef-Guard, but unfortunately I don't dare to give a new estimated release date for it :wink:

**Comment by Tyrael** [comment]
anything I can help with? do you have any abstract or specific about how should be the integration done? like should it be just a duplicate of the current github functionality but changed to match the gitlab api, or should those two be merged and being on github or gitlab should be a simply configuration option?

**Comment by svanharmelen** [comment]
Seems like the hardest part is done: https://github.com/xanzy/go-gitlab :smiley:

So will move on to implementing this into Chef-Guard starting next week...

**Comment by Tyrael** [comment]
nice!

**Comment by svanharmelen** [comment]
Fixed by latest Chef-Guard release (v0.6.0 PR #97)
