### ISSUE TITLE
Chef Guard commits empty commits

### ISSUE THREAD

**Issue by Tech356** [schubergphilis/chef-guard#64]
If I update a group of roles (but not all my roles) and upload them all, Chef guard will commit roles that haven't changed. 

```
knife role from file roles/test*.json
```

Any roles that haven't changed will get a commit with `0 changed files with 0 additions and 0 deletions.` A diff email will not be sent for this commit.

I think Chef Guard should not commit changes that don't change anything.

**Comment by svanharmelen** [comment]
Hmm.. Thanks, will have a look at this one shortly!

**Comment by svanharmelen** [comment]
Fixed by PR #74
