### ISSUE TITLE
Windows line endings cause Chef Guard to fail cookbook compare

### ISSUE THREAD

**Issue by Tech356** [schubergphilis/chef-guard#72]
The default for the git installation on Windows is:

```
Checkout Windows-style, commit Unix-style line endings
```

This causes Chef Guard to fail with "Cookbook Compare errors" since the local files have `\r\n` and the repo has `\n` line endings. It would be nice for Chef Guard to ignore line endings when comparing files.

**Comment by svanharmelen** [comment]
Fixed by PR #77
