### ISSUE TITLE
chef/erchef ports confusion

### ISSUE THREAD

**Issue by oker1** [schubergphilis/chef-guard#78]
I'm trying to run chef-guard on my machine, and I'm confused with the listen, erchefport, port parameters. Seems like guard uses the listen parameter and the erchefport to bind to. I would want chef-guard to listen on a different port then the chef server on the same host, and it seems like a config option is missing for it.

**Comment by svanharmelen** [comment]
@oker1 did you have a look at these pages: [default_section](http://xanzy.io/projects/chef-guard/configuration/default_section.html) and [chef_section](http://xanzy.io/projects/chef-guard/configuration/chef_section.html)? They explain the most part of your questions I think...

In short, the `listen` parameter determines on what IP Chef-Guard will bind. The port it will bind to is the same as the `erchefport` you configured. So the `erchefport` is actually used twice this way. It's used to configure the port CG binds to and at the same time it tells CG on what port the ErChef API is listening.

I can understand why this confuses you and maybe we should add a specific parameter to configure the port CG should bind to.

Lastly the `port` parameter is used only to specify on what port your Chef server is configured te listen for external (from other servers) traffic. So the `server` and `port` parameters are specifying server URL and port to access your Chef server.

Does this help?

**Comment by oker1** [comment]
Thanks for the clarification. The documentation does not specify this behavior clearly.

The additional parameter would be great, that would make everything explicit and easy to understand IMHO. That way you don't have to create a loopback interface with a 127.0.0.x ip address to be able to run the chef server and chef-guard on the same host.

**Comment by svanharmelen** [comment]
@oker1 you don't have to create an additional loopback interface. You can just bind to 127.0.0.2 without any additional config! Give it a try... That is actually why we set it up this way, it needs the least impact/changes on your Chef server (we also run the services on the same hosts).

Will look at adding a parameter in the next release coming up shortly. Thanks for your feedback!

**Comment by oker1** [comment]
On Mac OS I needed to add an alias to the loopback interface: `sudo ifconfig lo0 alias 127.0.0.2 up`

**Comment by svanharmelen** [comment]
Check... So for testing locally on Mac OSX your right, but you don't run your Chef server on Mac OSX right :wink:

**Comment by oker1** [comment]
I'm running goiardi as chef server, but this is just experimenting not production of course :)

**Comment by svanharmelen** [comment]
Nice! So let me know if you stumble upon any other issues... You can also (most of the time) find me on the IRC channel #chef-guard for quick questions or suggestions.

**Comment by svanharmelen** [comment]
Fixed by latest Chef-Guard release (v0.6.0 PR #97)
