### ISSUE TITLE
Chef 12 Support

### ISSUE THREAD

**Issue by hh** [schubergphilis/chef-guard#80]
I couldn't find any reference to Chef 12.

Could we update the documentation  at http://xanzy.io/projects/chef-guard/installation/prerequisites.html to explicit regarding the supported versions of Chef?

Cheers,
-chris

**Comment by svanharmelen** [comment]
@hh sure thing! If your up for it, just make a PR on the [website repo](https://github.com/xanzy/xanzy.github.io).

If not I'll have a look a little later on. I'm currently trying to get to a new release (in between some other projects) which will needs some document updates anyway.

Thx!

**Comment by hh** [comment]
Is anyone using this with Chef 12? I was thinking about updating the docs, but I'm not sure what's been tested.

**Comment by svanharmelen** [comment]
@hh CG is fully tested with Chef 12, so any PR's will by much appreciated :smiley: 

Edit: I just (this week) picked up work on CG again. So the long waited release with, among a lot of small tweaks and bug fixes, GitLab support will be due end of next week. Some additional docs will be needed for that as well.

**Comment by hh** [comment]
GitLab support would be great? What git services are currently supported?

**Comment by svanharmelen** [comment]
Currently only GitHub (both .com and enterprise)

**Comment by sbotman** [comment]
Think the gitlab support is finished by now... so you can close....

**Comment by svanharmelen** [comment]
@sbotman not only that, but it's also all documented correctly now... So this can indeed be closed :wink:
