### ISSUE TITLE
chef-guard not respecting chefignore

### ISSUE THREAD

**Issue by miguelaferreira** [schubergphilis/chef-guard#81]
I have a cookbook with some test fixtures under directory `test`. I have added the line `*/test` to the file `chefignore` that is in my cookbook directory.
When I do a `knife cookbook upload` command chef-guard reports a compare error, as follows:

``` bash
ERROR: Precondition Failed
Response: 
=== Cookbook Compare errors found ===
The source cookbook contains more files than your upload:
 - test/fixtures/data_bags/sql_server/credentials.json
 - test/fixtures/encrypted_data_bag_secret
 - test/fixtures/environments/test.json
```

It seems that knife ignores these files accordingly, but chef-guard does not.

**Comment by svanharmelen** [comment]
@miguelaferreira the chefignore file uses a different syntax as the gitignore file. So you would need to add this instead:

```
test/*
```

And of course make sure that is also committed into your repo as it will take the committed version over your local version.

**Comment by miguelaferreira** [comment]
@svanharmelen You are right!! That fixed it.

Thanks
