### ISSUE TITLE
How to check why tests are not working

### ISSUE THREAD

**Issue by akoldaev** [schubergphilis/chef-guard#83]
Hey. Sorry can't find anyone using chef-guard on IRC, so asking here.

I've just installed chef-guard and not sure if everything is configured correctly. However there're no errors in logs and it creates commits in `config` repo for each uploaded cookbook, so I assume it works.

The problem is it looks like it's not running tests for some reason. I'm checking the cookbooks locally with rubocop and foodcritic and they both give lots of errors.  However it gets uploaded just fine.
Both rubocop and foodcritic have correct paths in config and exist on the server.

My config:

```
[default]
  listen = 127.0.0.2
  logfile = /var/log/chef-guard.log
  tempdir = /var/tmp/chef-guard
  mode = silent
  maildomain =
  mailserver =
  mailport = 25
  mailrecipient =
  validatechanges = permissive
  commitchanges = true
  mailchanges = false
  searchgithub = true
  publishcookbook = false
  blacklist =
  gitorganization = 123
  gitcookbookorgs = 123
  includefcs =
  excludefcs =

[chef]
  enterprisechef = false
  server = chef.123
  port = 443
  sslnoverify = false
  erchefip = 127.0.0.1
  erchefport = 8000
  version = 11.12.4
  user = chef-guard
  key = /opt/chef-guard/chef-guard.pem
  s3key = 123
  s3secret = 123

[community]
  supermarket = https://supermarket.getchef.com
  forks =

[supermarket]
  server = supermarket.company.com
  port = 443
  sslnoverify = false
  version = 11.12.0
  user = chef-guard
  key = /opt/chef-guard/supermarket.pem

[graphite]
  server =
  port = 2003

[chefclients]
  path = /opt/chef-guard/clients

[tests]
  foodcritic = /opt/chef/embedded/bin/foodcritic
  rubocop = /opt/chef/embedded/bin/rubocop

[github "123"]
  sslnoverify = false
  token = 123
```

**Comment by svanharmelen** [comment]
@iroller I'm on IRC most of the time (#chef-guard) but it's no problem ask these kinds of questions here as well!

Don't know if you had a look at the cookbook upload [workflow](http://xanzy.io/projects/chef-guard/workflows/cookbook_upload.html) already? That one gives a good view on all the steps taken in different situations and configurations.

I notice in your config that the `mode` is set to `silent`. In this mode (again see the workflow for details) the checks are not done at all. So you need to change the `mode` to at least `permissive`.

Additionally you need to make sure you freeze the cookbook your uploading (when your done testing). If you look at the workflow you'll see that the tests are only executed when freezing a cookbook.

The reasoning for that is that while you are developing/testing a cookbook, you don't want these test to be triggered every time you upload. But when your done testing and want to freeze the cookbook so you can pin it in your environment, you want to double check all is good before actually freezing the cookbook.

Of course you could/should have checked that yourself locally before uploading, so this is just a verification that all is good...

Does this help/makes sense?

**Comment by akoldaev** [comment]
Thanks @svanharmelen, that definitely helps. For some reason I was sure I'm using "permissive" mode, didn't realize it was "validatechanges" => "permissive", and not mode.
