### ISSUE TITLE
Using berkshelf-api instead of private supermarket

### ISSUE THREAD

**Issue by akoldaev** [schubergphilis/chef-guard#87]
@svanharmelen suggested it should be fine to use berks-api url in [supermarket] section. However I'm getting the following error and not sure what causes it:

```
ERROR:   2015/03/13 22:16:37 Failed to get cookbook info from https://my-chef-server:443//cookbooks/mycookbook/versions/0_2_28: <!DOCTYPE html>
404 ...
```

It's Chef 11.
The correct url for that cookbook will be "https://my-chef-server:443/cookbooks/mycookbook/0.2.28" (According to chef webui).

**Comment by svanharmelen** [comment]
@iroller thanks for trying/testing! As I mentioned I didn't actually test this use case, so not to surprised that you encountered a problem :wink:

So what version of the berks-api are you using?

**Comment by akoldaev** [comment]
It's 2.1.0.

Here's my config file:

``` json
{
  "endpoints": [
    {
      "type": "chef_server",
      "options": {
        "url": "https://my-chef-server",
        "client_name": "clientname",
        "client_key": "/etc/chef/client.pem"
      }
    },
    {
      "type": "supermarket",
      "options": {
        "url": "https://supermarket.getchef.com"
      }
    }
  ]
}
```

Any chance I can re-build CG with some debugging enabled to provide more info?

And I've tried both latest release of CG and latest master - all the same.

**Comment by svanharmelen** [comment]
Yeah, this is not something that is actively used and/or tested so it's behaviour will be unchanged in master...

This has to do with the response received from the berks-api. The URL pointing to the cookbook download location looks a little different as you would get when it's pointing to a supermarket, so we need to check if it's worth the effort to support this use case as well.

I think it wouldn't be to difficult to hack support in, but need to have  closer look first so labeled this as an enhancement for now.

**Comment by svanharmelen** [comment]
Closing this one as a `won't fix`... This issue is pretty old by now and I don't have the incentive to add this myself. Of course PR's are always welcome :wink:
