### ISSUE TITLE
Option to only allow cookbook uploads with --freeze

### ISSUE THREAD

**Issue by Tech356** [schubergphilis/chef-guard#89]
I have an environment with 2 chef servers. One for development and test and another for production. I would like to be able to only allow frozen cookbooks to be uploaded to the production server. The cookbook should be fully tested on the dev server prior to being uploaded to the production server.

If the cookbook is not uploaded with `--freeze` then chef-guard would throw and error and disallow the upload.

**Comment by svanharmelen** [comment]
Hmm... I don't think that will become a feature as it doesn't really fit into the processes CG tries to enforce. If you configure CG correctly you will not be able to constrain or pin a cookbook anywhere as long as it's not frozen. So in effect you then have the same insurance right?

**Comment by Tech356** [comment]
OK. That makes sense. I think that will fit my needs. Thanks.
