### ISSUE TITLE
Cookbook upload gives 502 after adding rubocop dotfiles

### ISSUE THREAD

**Issue by akoldaev** [schubergphilis/chef-guard#90]
Getting weird error when trying to upload a cookbook with .rubocop.yml or .rubocop_todo.yml. I've tried disabling chef-guard and it uploads just fine.

Removing rubocop dotfiles also helps to proceed the upload. I guess it's something to do with rubocop check?

Using or not "--freeze" and "--force" flags don't change anything.

```
knife cookbook upload base --freeze


ERROR: Server returned error 502 for https://chef-server/organizations/myorg/cookbooks/base/0.1.31, retrying 3/5 in 10s

DEBUG: ---- HTTP Response Body ----

DEBUG: Failed to dowload .rubocop.yml from the base cookbook: <HTML><HEAD><TITLE>404 Not Found</TITLE></HEAD><BODY><H1>Not Found</H1>The requested document was not found on this server.<P><HR><ADDRESS>mochiweb+webmachine web server</ADDRESS></BODY></HTML>

DEBUG: Failed to dowload .rubocop_todo.yml from the base cookbook: <HTML><HEAD><TITLE>404 Not Found</TITLE></HEAD><BODY><H1>Not Found</H1>The requested document was not found on this server.<P><HR><ADDRESS>mochiweb+webmachine web server</ADDRESS></BODY></HTML>

10.10.0.113 - - [04/May/2015:06:35:29 +0000]  "PUT /organizations/myorg/cookbooks/base/0.1.31?force=true HTTP/1.1" 502 "1.018" 252 "-" "Chef Knife/12.3.0 (ruby-2.2.2-p95; ohai-8.3.0; x86_64-darwin14; +http://opscode.com)" "127.0.0.2:8000" "502" "1.007" "12.3.0" "algorithm=sha1;version=1.0;" "username" "2015-05-04T06:35:16Z" "c8X6nWm9xI0G2C+IVXC/+1EKI=" 6658
```

**Comment by akoldaev** [comment]
And it also works fine if I bump the version and don't use `--freeze` flag, so it's definitely something to do with rubocop check being executed by chef-guard.

**Comment by svanharmelen** [comment]
@iroller this isn't related to the execution of `rubocop`, but to the way a cookbook is uploaded by knife and/or CG. Will look into this one...

**Comment by akoldaev** [comment]
Thanks @svanharmelen, really annoying bug, having to --force for now pretty much everywhere

**Comment by svanharmelen** [comment]
Hi @iroller! Is this still an issue with the latest version? If not I'm going to close this before the end of the year to cleanup old/stale issues. Thanks!

**Comment by akoldaev** [comment]
Hi there. Sorry, haven't been using any of the related software in a while. Closing for now.
