### ISSUE TITLE
Debug logging

### ISSUE THREAD

**Issue by akoldaev** [schubergphilis/chef-guard#92]
It's feature request. Sometimes when using CG I see random 502s and sometimes it doesn't actually upload cookbook showing no output on STDOUT, zero exit code and nothing in console.log or chef-guard.log. It's really hard to catch those problems when there's no option for really verbose logging mode.
I guess Go should allow to log lots of info about every single step? It'd be very useful.

**Comment by svanharmelen** [comment]
@iroller having debug logging is not Go specific or even Go related, it's a matter of coding in all the stuff you would like to have logged. I think at the moment CG logs quite a lot, so I'm unsure what type of logging you would like to see here?

On the other hand some say you can never have enough logging, but like I said it's not something you can just turn on or off, you have to program in everything you think is worth logging. So this should be an ongoing effort where you add some logging when you learn that a certain part in the code can cause issues that are currently not logged sufficiently.

The examples you give sound more like bugs that need to be solved. They should output what went wrong, so it seems the errors aren't caught correctly...

**Comment by akoldaev** [comment]
I figured one of those issues. I provided Chef-Guard a bad script-wrapper for rubocop and when CG executed that script it was just hanging and waiting for user input because I forgot to pass arguments to that wrapper.

The thing is all the logfiles were empty and I was getting 502. I was only able to figure out this when I looked at the process list and noticed there's my wrapper. So what I'm talking here about is to have an option for Chef-Guard to post every step it's about to perform to the logfile first so it's easier to debug.

**Comment by svanharmelen** [comment]
Check... So I would say this requires two things:
1. Make de loglevel a configurable option 
2. Add additional logging for (at least) loglevel `debug`

Will leave this issue open until the first requirement is in, as the second requirement should be an ongoing effort which can be done my multiple PR's from multiple people whenever you find some logging is missing or incomplete.

**Comment by svanharmelen** [comment]
Even though this is a very valid point, for now I'm going to close this one as `won't fix`. Of course PR's are always welcome and maybe I get to this myself at any point in the future, but for now I'm not going to add this myself.
