### ISSUE TITLE
When configured to use Github, in case of a Github error only block relevant calls

### ISSUE THREAD

**Issue by svanharmelen** [schubergphilis/chef-guard#95]
When Github is down or unreachable for whatever reason, we should make sure CG can continue to function as much as possible. So only calls that are dependant on Github should fail. Other calls that only do a search against Github while searching for the source of a cookbook, should just continue and treat the error as if the cookbook was not found on Github.

This will allow cookbook searches to successfully find all other cookbooks located in the Supermarket or an internal Github appliance without any errors.

**Comment by akoldaev** [comment]
Huge :+1: here

**Comment by svanharmelen** [comment]
Closing this issue for now. I would be an improvement, but the last 2 years this happened maybe once. So there is not much incentive to spend time on this one.
