### ISSUE TITLE
Supermarket upload fails when using ridley

### ISSUE THREAD

**Issue by akoldaev** [schubergphilis/chef-guard#96]
There's a very popular Chef API client https://github.com/reset/ridley, we're using it in our environment for establishing specific chef workflow. When I'm enabling "publishcookbooks" in chef-guard it works fine with "knife cookbook upload", but fails with the following errors when using ridley for the same cookbook:

```
==> /var/log/chef-guard.log <==
ERROR:   2015/06/17 00:34:16 Failed to upload mycookbook to the Supermarket: Multipart POST part 'tarball' must contain a metadata.json entry.;Multipart POST part 'tarball' must contain a non-empty README.
```

This cookbook has both "README.md" and "metadata.rb", but ridley might be using it's own way to upload [metadata](https://github.com/reset/ridley/blob/8dfb7b4dd5446f82c4dae73e39d5fc83634e786f/lib/ridley/resources/cookbook_resource.rb#L208) and README (looks like it's not uploading it at all).

Here's the code I'm using to upload a cookbook using ridley:

``` ruby
require 'ridley'
ridley = Ridley.new(server_url: @chef_config[:chef_server_url],
  client_name: @chef_config[:node_name],
  client_key: @chef_config[:client_key])
ridley.cookbook.upload(Dir.pwd,
  name:     metadata.name,
  force:    options[:force],
  freeze:   options[:freeze])
```

It'd be really nice if chef-guard could support uploads through ridley.
As a temporary quick solution it'd be great to have an option in chef-guard to skip those checks.

EDIT: although I'm not 100% if supermarket will accept such cookbook if we skip checks for readme and metadata in chef-guard. So not sure if publishing cookbooks using chef-guard when uploading with ridley can work at all.

**Comment by svanharmelen** [comment]
@iroller yeah I know the ridley stuff and as far as I know it should work together with CG and the Supermarket.

The error you currently get is not a CG error, but an error passed through from the Supermarket. So there is nothing that we can do in CG to fix this. But I've seen this before so I have a couple of suggestion how to get past these errors.

It seems that the Supermarket is pretty picky when it comes to the layout and naming of the uploaded TAR file. So one thing that you should check is if the Github repo name and the cookbook name (as written in the metadata.rb) are the same? In most cases these kind of errors have to do with the way the Supermarket unpacks and reads the uploaded TAR file.

**Comment by akoldaev** [comment]
Oh I thought those errors are coming from CG. Github repo matches the cookbook name. I'll try digging into it more tomorrow

**Comment by svanharmelen** [comment]
Yeah, then check if you're actually creating the metadata.json in your upload? Maybe it searches for that one and cannot find it?

I know Berkshelf also uses the ridley stuff and uploading (incl. publishing) works just fine with it. So maybe check that source as well for insights?

**Comment by akoldaev** [comment]
> I know Berkshelf also uses the ridley stuff and uploading (incl. publishing) works just fine with it. So maybe check that source as well for insights?

I didn't find the publishing part in berkshelf. Doesn't look like it can upload cookbooks to supermarket.

Here's how knife performs the direct upload to supermarket: https://gist.github.com/iroller/fea822f1be740962f511

I checked the list of files being uploaded in ridley https://github.com/reset/ridley/blob/8dfb7b4dd5446f82c4dae73e39d5fc83634e786f/lib/ridley/resources/cookbook_resource.rb#L221 and it contains both  metadata.json and README.md, so these two files should be doing it to CG.

As far as I understand ridley itself doesn't create an archive. @svanharmelen could you point me on where CG gets tgz file [here](https://github.com/xanzy/chef-guard/blob/54728b35b30b2fc28d91ec47a44ec2f3bd5a7af0/supermarket.go#L51)? I want to add some debugging into CG to see what's in tar file prior to uploading to supermarket, but not exactly sure where to add it.

**Comment by svanharmelen** [comment]
@iroller I think the easiest and fastest way to understand what is going wrong here is if you could share a (dummy) cookbook that gives you this problem. Maybe together with a small cmd tool to upload the cookbook using your approach with the ridley api?

The line you refer to is where the multipart web request is being prepared. A [few lines below](https://github.com/xanzy/chef-guard/blob/54728b35b30b2fc28d91ec47a44ec2f3bd5a7af0/supermarket.go#L55) that you can see that the tarfile is written to the web request. So if you write that same data (the content of `cg.TarFile) to a file on disk, you could inspect the tarfile after the upload failed to see exactly what it looks like.

**Comment by akoldaev** [comment]
Hey @svanharmelen. Sorry for a delay. Here's a cookbook with instructions in README.md: https://github.com/iroller/cg-ridley

Could you please try and let me know if it works in your environment? I wonder if it's something specific to my setup or not.

**Comment by akoldaev** [comment]
Oh oops. Looks like I haven't looked into this issue since 0.6.0 update. It looks to be fixed and works just fine now. Feel free to close this bug, great work on 0.6.0!

It contains all the needed files now and doesn't produce an error:

```
tar -zxvf cookbook.tgz
cg-ridley/recipes/default.rb
cg-ridley/Gemfile
cg-ridley/Gemfile.lock
cg-ridley/metadata.json
cg-ridley/README.md
```

**Comment by svanharmelen** [comment]
:+1:

Thanks for the feedback!
