### ISSUE TITLE
Policyfiles support?

### ISSUE THREAD

**Issue by joelmoss** [schubergphilis/chef-guard#99]
Are there any plans to support Policyfiles?

**Comment by svanharmelen** [comment]
@joelmoss think it would be a nice enhancement, but at the moment it's not planned to add support for policy files.

Of course a PR adding support would be greatly appreciated! :wink:

**Comment by svanharmelen** [comment]
Closing this as a `won't fix` for now. Of course PR's are always welcome :wink:
